### ISSUE TITLE
Error in names

### ISSUE THREAD

**Issue by Jamalreyhani** [dsandwell/gmtsar#1]
There is errors in name of some files in new version. For example when I am typing "gmtsar.csh" to see the list of scripts, Sentinel's script name is "p2p_S1A_SLC.csh" but when I am running this code, I have got syntax error. Because the name of script is "p2p_S1_SLC.csh" whitout A. Please correct this.

**Comment by Xiaohua-Eric-Xu** [comment]
fixed
